# -*- coding: utf-8 -*-
"""Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1saLmgcmwxHx8dqcMnT2Zz9HR1n2MpaKw

##Análisis Exploratio de Datos - Delitos informativos
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime

df=pd.read_csv("/content/drive/MyDrive/Análisis de datos/Proyecto Análisis de Datos/Bases/Seleccionadas/Conteo_de_V_ctimas_V2_colab.csv", sep=",")
df



df.info

df.shape

df.columns

df.isnull().sum()

df['GRUPO_DELITO'].nunique()

df['PAÍS_NACIMIENTO'].nunique()

print(df.groupby("GRUPO_DELITO")["TOTAL_VÍCTIMAS"].sum().sort_values())

print(df.groupby("GRUPO_DELITO")["GRUPO_DELITO"].count().sort_values())

#print(df.groupby("TOTAL_VÍCTIMAS").sum().sort_values())
print(df["TOTAL_VÍCTIMAS"].sum())

di= df[df["GRUPO_DELITO"]=="DELITOS INFORMATICOS"]
dit =di.groupby("DELITO")["TOTAL_VÍCTIMAS"].sum().sort_values()
#dit["Nombre_Corto"] = dit["DELITO"].str.split("ART")
#VIOLENCIA INTRAFAMILIAR
dit
#print(dit.count())

dit.dtype

di

print(di.groupby("AÑO_HECHOS")["TOTAL_VÍCTIMAS"].sum().sort_values())

print(di.groupby("AÑO_HECHOS")["TOTAL_VÍCTIMAS"].sum())

print(di.groupby("DEPARTAMENTO_HECHO")["TOTAL_VÍCTIMAS"].sum().sort_values())

print(di["TOTAL_VÍCTIMAS"].sum())

#df["DELITO"].head(20)
abc = df["DELITO"].str.split("ART.")
abc.head(10)

print(df.DELITO[df.DELITO.str.contains("PORNOVENGANZA")])